# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 16:34
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=200)),
                ('airport_iata', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=200)),
                ('city_location', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('country_name', models.CharField(max_length=200)),
            ],
        ),
    ]
