# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 16:52
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='city_location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
